// Builds progress/tracker.json, progress/STATUS.md and progress/INDEX.md from:
//   progress/catalog.json          full problem list (scripts/sync-catalog.js)
//   progress/results.json          recorded LeetCode submission results (scripts/add-result.js)
//   progress/study-plans.json      study plans and their badges (scripts/sync-study-plans.js)
//   progress/account-snapshot.json latest numbers read from the logged-in LeetCode account
//   progress/badges.json           hand-verified badge / achievement tracker
// Nothing here is hard-coded: re-run after every sync or new result.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const load = (p) => JSON.parse(fs.readFileSync(path.join(root, p), 'utf8'));
const catalog = load('progress/catalog.json');
const { results } = load('progress/results.json');
const { plans } = load('progress/study-plans.json');
const snapshot = load('progress/account-snapshot.json');
const badges = load('progress/badges.json');

const accepted = new Map(results.filter((r) => r.status === 'Accepted').map((r) => [r.id, r]));
const problems = catalog.problems;
const accessible = problems.filter((p) => !p.premium);
const DIFFS = ['Easy', 'Medium', 'Hard'];

const bucketOf = (id) => {
  const lo = Math.floor((Number(id) - 1) / 100) * 100 + 1;
  return `${String(lo).padStart(4, '0')}-${String(lo + 99).padStart(4, '0')}`;
};
const dirOf = (p) => `solutions/${bucketOf(p.id)}/${p.id.padStart(4, '0')}-${p.slug}`;
const langFor = (p) =>
  p.categories.includes('algorithms') || p.categories.includes('javascript') ? 'javascript'
    : p.categories.includes('shell') ? 'bash'
    : p.categories.includes('concurrency') ? 'not available in JavaScript'
    : p.categories.includes('database') ? 'sql'
    : 'python (pandas)';

// ---- aggregate stats ----
const byDifficulty = Object.fromEntries(
  DIFFS.map((d) => {
    const all = problems.filter((p) => p.difficulty === d);
    const acc = all.filter((p) => !p.premium);
    return [d, { listed: all.length, accessible: acc.length, solved: all.filter((p) => accepted.has(p.id)).length }];
  }),
);
const categories = {};
for (const p of problems) {
  const c = p.categories[0];
  categories[c] ??= { listed: 0, accessible: 0, solved: 0, language: langFor(p) };
  categories[c].listed++;
  if (!p.premium) categories[c].accessible++;
  if (accepted.has(p.id)) categories[c].solved++;
}
const topics = {};
for (const p of accessible) {
  for (const t of p.topics) {
    topics[t] ??= { accessible: 0, solved: 0 };
    topics[t].accessible++;
    if (accepted.has(p.id)) topics[t].solved++;
  }
}
const studyPlans = plans.map((pl) => {
  const qs = pl.groups.flatMap((g) => g.questions);
  return {
    slug: pl.slug,
    name: pl.name,
    badge: pl.badge,
    premiumPlan: pl.premiumPlan,
    listed: qs.length,
    listIncomplete: pl.partial,
    premiumQuestions: pl.premiumQuestions.length,
    solved: qs.filter((q) => accepted.has(q.id)).length,
  };
});

const solvedCount = problems.filter((p) => accepted.has(p.id)).length;
const tracker = {
  generatedAt: new Date().toISOString(),
  catalogFetchedAt: catalog.fetchedAt,
  totals: {
    listed: catalog.totalListed,
    accessible: accessible.length,
    premium: problems.length - accessible.length,
    solved: solvedCount,
    unsolvedAccessible: accessible.filter((p) => !accepted.has(p.id)).length,
  },
  byDifficulty,
  byCategory: categories,
  topics,
  studyPlans,
  account: snapshot,
  badges,
};
fs.writeFileSync(path.join(root, 'progress/tracker.json'), JSON.stringify(tracker, null, 2) + '\n');

// ---- STATUS.md ----
const pct = (a, b) => (b ? `${((100 * a) / b).toFixed(1)}%` : '—');
const topicRows = Object.entries(topics)
  .sort((a, b) => b[1].accessible - a[1].accessible)
  .map(([t, v]) => `| ${t} | ${v.solved} / ${v.accessible} | ${pct(v.solved, v.accessible)} |`);
const status = `# Progress

Generated by \`scripts/build-tracker.js\` at ${tracker.generatedAt}. Catalog fetched from LeetCode at ${catalog.fetchedAt}.
Solved counts come only from recorded LeetCode results ([results.json](results.json)); the account snapshot below is
read from the logged-in LeetCode profile.

## Overall

| | Count |
|---|---|
| Problems listed on LeetCode | ${tracker.totals.listed} |
| Accessible (not Premium-only) | ${tracker.totals.accessible} |
| Premium-only (not accessible to this account) | ${tracker.totals.premium} |
| **Solved (Accepted)** | **${solvedCount}** |
| Accessible and not yet solved | ${tracker.totals.unsolvedAccessible} |

| Difficulty | Solved | Accessible | Listed |
|---|---|---|---|
${DIFFS.map((d) => `| ${d} | ${byDifficulty[d].solved} | ${byDifficulty[d].accessible} | ${byDifficulty[d].listed} |`).join('\n')}

| Category | Solved | Accessible | Listed | Language |
|---|---|---|---|---|
${Object.entries(categories).map(([c, v]) => `| ${c} | ${v.solved} | ${v.accessible} | ${v.listed} | ${v.language} |`).join('\n')}

## Account snapshot (read from LeetCode ${snapshot.capturedAt})

| | |
|---|---|
| Solved shown on profile | ${snapshot.solved} / ${snapshot.totalListed} |
| Easy · Medium · Hard | ${snapshot.easy} · ${snapshot.medium} · ${snapshot.hard} |
| Current streak | ${snapshot.streak} |
| Today's Daily Challenge (${snapshot.dailyDate}) | ${snapshot.dailyStatus} |
| Badges shown on profile | ${snapshot.badges.length ? snapshot.badges.join(', ') : 'none'} |

## Study plans with badges

| Plan | Badge | Solved / listed | Premium-only questions | Notes |
|---|---|---|---|---|
${studyPlans.map((s) => `| ${s.name} | ${s.badge ?? '—'} | ${s.solved} / ${s.listed} | ${s.premiumPlan ? 'whole plan' : s.premiumQuestions} | ${s.listIncomplete ? 'some groups not visible via API; verify on the plan page' : ''} |`).join('\n')}

## Topic coverage (accessible problems)

| Topic | Solved / accessible | % |
|---|---|---|
${topicRows.join('\n')}
`;
fs.writeFileSync(path.join(root, 'progress/STATUS.md'), status);

// ---- INDEX.md ----
const complexityOf = (dir) => {
  const f = path.join(root, dir, 'NOTES.md');
  if (!fs.existsSync(f)) return '';
  const m = fs.readFileSync(f, 'utf8').match(/## Complexity\n([\s\S]*?)\n\n/);
  if (!m) return '';
  const bigO = /O\((?:[^()]|\([^()]*\))*\)/; // first O(...) on the line, allowing one level of nesting
  return m[1]
    .split('\n')
    .map((l) => {
      const label = (l.match(/(Time|Space|Build|Each)[^:]*/) || [''])[0];
      const o = (l.match(bigO) || [''])[0];
      return o ? `${label}: ${o}` : '';
    })
    .filter(Boolean)
    .join('; ')
    .replace(/\|/g, '\\|'); // keep markdown table columns intact (e.g. O(|s|·|t|))
};
const rows = problems
  .filter((p) => accepted.has(p.id))
  .map((p) => {
    const r = accepted.get(p.id);
    const dir = dirOf(p);
    return `| ${p.id} | [${p.title}](https://leetcode.com/problems/${p.slug}/) | ${p.difficulty} | ${p.topics.slice(0, 4).join(', ')} | [solution](../${dir}/) | ${r.status} (${r.tests}) | ${r.solvedOn}${r.dailyDate ? ' · **daily**' : ''} | ${complexityOf(dir)} |`;
  });
fs.writeFileSync(
  path.join(root, 'progress/INDEX.md'),
  `# Solved problem index\n\nGenerated by \`scripts/build-tracker.js\`. One row per problem accepted on LeetCode.\n\n| # | Problem | Difficulty | Topics | Files | LeetCode result | Solved | Complexity |\n|---|---|---|---|---|---|---|---|\n${rows.join('\n')}\n`,
);
console.log(`tracker: ${solvedCount} solved / ${accessible.length} accessible / ${catalog.totalListed} listed`);
