// Regenerates progress/STATUS.md from progress/problems.json + progress/results.json.
// results.json is filled in by hand from LeetCode's own submission results.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const problems = JSON.parse(fs.readFileSync(path.join(root, 'progress/problems.json'), 'utf8'));
const { results } = JSON.parse(fs.readFileSync(path.join(root, 'progress/results.json'), 'utf8'));
const byId = new Map(results.map((r) => [r.id, r]));

const rows = problems.map((p) => {
  const r = byId.get(p.id);
  const result = r ? `${r.status} (${r.tests})` : 'pending';
  const counted = !r ? '—' : r.daily ? '**Daily**' : 'Late';
  const dir = `../solutions/2026/09/${p.date.slice(8)}-${String(p.id).padStart(4, '0')}-${p.slug}/`;
  return `| ${p.date.slice(5)} | ${p.id} | [${p.title}](${dir}) | ${p.difficulty} | ${result} | ${counted} |`;
});

const solved = problems.filter((p) => byId.get(p.id)?.status === 'Accepted');
const count = (d) => solved.filter((p) => p.difficulty === d).length;

const md = `# Progress: September 2026 Daily Challenge problems

Generated by \`scripts/build-status.js\`. Results are copied from LeetCode's own submission results, not from local tests.

- **Daily**: accepted inside the problem's original 24-hour Daily Challenge window.
- **Late**: accepted after the window closed. It counts as a solved problem, not as a completed Daily Challenge (the calendar day stays missed).

**Accepted: ${solved.length} / ${problems.length}** (Easy ${count('Easy')}, Medium ${count('Medium')}, Hard ${count('Hard')})

| Date | # | Problem | Difficulty | LeetCode result | Counted as |
|---|---|---|---|---|---|
${rows.join('\n')}
`;
fs.writeFileSync(path.join(root, 'progress/STATUS.md'), md);
console.log(`STATUS.md: ${solved.length}/${problems.length} accepted`);
